## Objective: Use Python to perform a Vlookup-eqivalent of merging a column ('Regional indicator') from one dataset to another

## Step 1: Import pandas library

In [1]:
import pandas as pd

## Step 2: Create dataframes for datasets that are in Excel format and view the first 5 rows of each dataframe

In [2]:
country_df = pd.read_excel('DataPanelWHR2021C2.xls')
region_df = pd.read_excel('DataForFigure2.1WHR2021C2.xls')

In [3]:
country_df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.723590,7.370100,0.450662,50.799999,0.718114,0.167640,0.881686,0.517637,0.258195
1,Afghanistan,2009,4.401778,7.539972,0.552308,51.200001,0.678896,0.190099,0.850035,0.583926,0.237092
2,Afghanistan,2010,4.758381,7.646709,0.539075,51.599998,0.600127,0.120590,0.706766,0.618265,0.275324
3,Afghanistan,2011,3.831719,7.619532,0.521104,51.919998,0.495901,0.162427,0.731109,0.611387,0.267175
4,Afghanistan,2012,3.782938,7.705479,0.520637,52.240002,0.530935,0.236032,0.775620,0.710385,0.267919

In [4]:
region_df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8421,0.031646,7.904126,7.780075,10.775202,0.953603,72.000000,0.949268,-0.097760,0.185846,2.430343,1.446356,1.106192,0.740824,0.690577,0.124200,0.480524,3.253415
1,Denmark,Western Europe,7.6195,0.034657,7.687428,7.551572,10.933176,0.954410,72.699753,0.945639,0.030109,0.178838,2.430343,1.501548,1.108008,0.762862,0.686160,0.207615,0.484993,2.868296
2,Switzerland,Western Europe,7.5715,0.036243,7.642536,7.500463,11.117368,0.941742,74.400101,0.918788,0.024629,0.291698,2.430343,1.565899,1.079469,0.816415,0.653488,0.204040,0.413019,2.839148
3,Iceland,Western Europe,7.5539,0.059373,7.670271,7.437528,10.877768,0.982938,73.000000,0.955123,0.160274,0.672865,2.430343,1.482190,1.172279,0.772319,0.697701,0.292526,0.169940,2.966945
4,Netherlands,Western Europe,7.4640,0.027326,7.517559,7.410441,10.931812,0.941601,72.400116,0.913116,0.175404,0.337938,2.430343,1.501072,1.079151,0.753425,0.646585,0.302397,0.383531,2.797818

## Step 3: Keep only the column with region names for the respective countries and view the first 5 rows of the new dataframe

In [5]:
region_df_new = region_df.filter(['Country name', 'Regional indicator'])

In [6]:
region_df_new.head()

  Country name Regional indicator
0      Finland     Western Europe
1      Denmark     Western Europe
2  Switzerland     Western Europe
3      Iceland     Western Europe
4  Netherlands     Western Europe

## Step 4: Merge both dataframes to reflect the region names for the respective countries

In [7]:
merged_df = country_df.merge(region_df_new, on = 'Country name', how = 'left')

In [8]:
merged_df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Regional indicator
0,Afghanistan,2008,3.723590,7.370100,0.450662,50.799999,0.718114,0.167640,0.881686,0.517637,0.258195,South Asia
1,Afghanistan,2009,4.401778,7.539972,0.552308,51.200001,0.678896,0.190099,0.850035,0.583926,0.237092,South Asia
2,Afghanistan,2010,4.758381,7.646709,0.539075,51.599998,0.600127,0.120590,0.706766,0.618265,0.275324,South Asia
3,Afghanistan,2011,3.831719,7.619532,0.521104,51.919998,0.495901,0.162427,0.731109,0.611387,0.267175,South Asia
4,Afghanistan,2012,3.782938,7.705479,0.520637,52.240002,0.530935,0.236032,0.775620,0.710385,0.267919,South Asia

## Step 5A: View the column names by using a list

In [9]:
merged_df_col_names = merged_df.columns.tolist()

merged_df_col_names

['Country name',
 'year',
 'Life Ladder',
 'Log GDP per capita',
 'Social support',
 'Healthy life expectancy at birth',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Positive affect',
 'Negative affect',
 'Regional indicator']

## Step 5B: Reorder columns in merged dataframe by moving 'Regional indicator' from last column to second column (i.e. after 'Country name') and modify naming convention

In [10]:
merged_df = merged_df[['Country name', 'Regional indicator', 'year', 'Life Ladder', 'Log GDP per capita',
                       'Social support', 'Healthy life expectancy at birth', 'Freedom to make life choices',
                       'Generosity', 'Perceptions of corruption', 'Positive affect', 'Negative affect']]

merged_df.head()

,Country name,Regional indicator,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,South Asia,2008,3.723590,7.370100,0.450662,50.799999,0.718114,0.167640,0.881686,0.517637,0.258195
1,Afghanistan,South Asia,2009,4.401778,7.539972,0.552308,51.200001,0.678896,0.190099,0.850035,0.583926,0.237092
2,Afghanistan,South Asia,2010,4.758381,7.646709,0.539075,51.599998,0.600127,0.120590,0.706766,0.618265,0.275324
3,Afghanistan,South Asia,2011,3.831719,7.619532,0.521104,51.919998,0.495901,0.162427,0.731109,0.611387,0.267175
4,Afghanistan,South Asia,2012,3.782938,7.705479,0.520637,52.240002,0.530935,0.236032,0.775620,0.710385,0.267919

In [11]:
merged_df = merged_df.rename(columns = {'Country name': 'Country_name', 'Regional indicator': 'Regional_indicator', 'year': 'Year',
                                        'Life Ladder': 'Life_Ladder', 'Log GDP per capita': 'Log_GDP_per_capita', 'Social support': 'Social_support',
                                        'Healthy life expectancy at birth': 'Healthy_life_expectancy_at_birth',
                                        'Freedom to make life choices': 'Freedom_to_make_life_choices',
                                        'Perceptions of corruption': 'Perceptions_of_corruption', 'Positive affect': 'Positive_affect',
                                        'Negative affect': 'Negative_affect'})

merged_df.head()

,Country_name,Regional_indicator,Year,Life_Ladder,Log_GDP_per_capita,Social_support,Healthy_life_expectancy_at_birth,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,Positive_affect,Negative_affect
0,Afghanistan,South Asia,2008,3.723590,7.370100,0.450662,50.799999,0.718114,0.167640,0.881686,0.517637,0.258195
1,Afghanistan,South Asia,2009,4.401778,7.539972,0.552308,51.200001,0.678896,0.190099,0.850035,0.583926,0.237092
2,Afghanistan,South Asia,2010,4.758381,7.646709,0.539075,51.599998,0.600127,0.120590,0.706766,0.618265,0.275324
3,Afghanistan,South Asia,2011,3.831719,7.619532,0.521104,51.919998,0.495901,0.162427,0.731109,0.611387,0.267175
4,Afghanistan,South Asia,2012,3.782938,7.705479,0.520637,52.240002,0.530935,0.236032,0.775620,0.710385,0.267919

## Step 6: Save merged dataframe to CSV format

In [12]:
merged_df.to_csv('HappinessDataTransformed.csv', index = False)